{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "E:\\Projecten\\Sepsis\\src\n"
     ]
    }
   ],
   "source": [
    "%cd ../src\n",
    "%pwd\n",
    "%matplotlib inline\n",
    "%load_ext autoreload\n",
    "%autoreload 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "from xgboost2.clinical_validation import read_data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2020-06-26 13:03:22,435 - root - INFO - clinical_validation : 73 - Reading data from file: model_1_out_3_maindb.csv\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\logging\\handlers.py\", line 69, in emit\n",
      "    self.doRollover()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\logging\\handlers.py\", line 393, in doRollover\n",
      "    self.rotate(self.baseFilename, dfn)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\logging\\handlers.py\", line 110, in rotate\n",
      "    os.rename(source, dest)\n",
      "PermissionError: [WinError 32] Het proces heeft geen toegang tot het bestand omdat het door een ander\n",
      "proces wordt gebruikt: 'E:\\\\Projecten\\\\Sepsis\\\\src\\\\logging\\\\scripts.log' -> 'E:\\\\Projecten\\\\Sepsis\\\\src\\\\logging\\\\scripts.log.2020-06-24_14'\n",
      "Call stack:\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\traitlets\\config\\application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 499, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 132, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\asyncio\\base_events.py\", line 539, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\asyncio\\base_events.py\", line 1775, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\ioloop.py\", line 758, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\stack_context.py\", line 300, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 1233, in inner\n",
      "    self.run()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 1147, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 346, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 259, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 513, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 294, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2817, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2843, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 67, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3018, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3183, in run_ast_nodes\n",
      "    if (yield from self.run_code(code, result)):\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3265, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-6-b2f79585e09d>\", line 7, in <module>\n",
      "    version = model_version_mort)\n",
      "  File \"E:\\Projecten\\Sepsis\\src\\xgboost2\\clinical_validation.py\", line 73, in read_data\n",
      "    logging.info(\"Reading data from file: {}\".format(model_file))\n",
      "Message: 'Reading data from file: model_1_out_3_maindb.csv'\n",
      "Arguments: ()\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2020-06-26 13:03:23,562 - root - INFO - clinical_validation : 88 - Selecting Y-value\n",
      "2020-06-26 13:03:23,567 - root - INFO - clinical_validation : 91 - Selecting X-values\n",
      "20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\logging\\handlers.py\", line 69, in emit\n",
      "    self.doRollover()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\logging\\handlers.py\", line 393, in doRollover\n",
      "    self.rotate(self.baseFilename, dfn)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\logging\\handlers.py\", line 110, in rotate\n",
      "    os.rename(source, dest)\n",
      "PermissionError: [WinError 32] Het proces heeft geen toegang tot het bestand omdat het door een ander\n",
      "proces wordt gebruikt: 'E:\\\\Projecten\\\\Sepsis\\\\src\\\\logging\\\\scripts.log' -> 'E:\\\\Projecten\\\\Sepsis\\\\src\\\\logging\\\\scripts.log.2020-06-24_14'\n",
      "Call stack:\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\traitlets\\config\\application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 499, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 132, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\asyncio\\base_events.py\", line 539, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\asyncio\\base_events.py\", line 1775, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\ioloop.py\", line 758, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\stack_context.py\", line 300, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 1233, in inner\n",
      "    self.run()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 1147, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 346, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 259, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 513, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 294, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2817, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2843, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 67, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3018, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3183, in run_ast_nodes\n",
      "    if (yield from self.run_code(code, result)):\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3265, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-6-b2f79585e09d>\", line 7, in <module>\n",
      "    version = model_version_mort)\n",
      "  File \"E:\\Projecten\\Sepsis\\src\\xgboost2\\clinical_validation.py\", line 88, in read_data\n",
      "    logging.info(\"Selecting Y-value\")\n",
      "Message: 'Selecting Y-value'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\logging\\handlers.py\", line 69, in emit\n",
      "    self.doRollover()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\logging\\handlers.py\", line 393, in doRollover\n",
      "    self.rotate(self.baseFilename, dfn)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\logging\\handlers.py\", line 110, in rotate\n",
      "    os.rename(source, dest)\n",
      "PermissionError: [WinError 32] Het proces heeft geen toegang tot het bestand omdat het door een ander\n",
      "proces wordt gebruikt: 'E:\\\\Projecten\\\\Sepsis\\\\src\\\\logging\\\\scripts.log' -> 'E:\\\\Projecten\\\\Sepsis\\\\src\\\\logging\\\\scripts.log.2020-06-24_14'\n",
      "Call stack:\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\traitlets\\config\\application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 499, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 132, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\asyncio\\base_events.py\", line 539, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\asyncio\\base_events.py\", line 1775, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\ioloop.py\", line 758, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\stack_context.py\", line 300, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 1233, in inner\n",
      "    self.run()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 1147, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 346, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 259, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 513, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 294, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2817, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2843, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 67, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3018, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3183, in run_ast_nodes\n",
      "    if (yield from self.run_code(code, result)):\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3265, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-6-b2f79585e09d>\", line 7, in <module>\n",
      "    version = model_version_mort)\n",
      "  File \"E:\\Projecten\\Sepsis\\src\\xgboost2\\clinical_validation.py\", line 91, in read_data\n",
      "    logging.info(\"Selecting X-values\")\n",
      "Message: 'Selecting X-values'\n",
      "Arguments: ()\n"
     ]
    }
   ],
   "source": [
    "# model 1\n",
    "model = 1\n",
    "model_version_mort = 22\n",
    "\n",
    "data_dict = read_data(model = model, \n",
    "                      out = 3, # mortality\n",
    "                      version = model_version_mort)\n",
    "\n",
    "labels = ['BGbinary', 'URESE', 'ALBSE', 'CKDESE', 'BGA',\n",
    "          'TRC', 'Geboortedatum', 'TEISE', 'AFSE', 'GLUVB',\n",
    "          'GLUAB', 'LDSE', 'LACAB', 'KRESE', 'LPSSE',\n",
    "          'TBISE', 'GGTSE', 'CRPSE', 'MAGSE', 'HB']\n",
    "print(len(labels))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'20': '0.818 (0.800-0.837)'}\n",
      "{'20': '0.818 (0.800-0.837)', '15': '0.808 (0.797-0.820)'}\n",
      "{'20': '0.818 (0.800-0.837)', '15': '0.808 (0.797-0.820)', '10': '0.795 (0.770-0.821)'}\n",
      "{'20': '0.818 (0.800-0.837)', '15': '0.808 (0.797-0.820)', '10': '0.795 (0.770-0.821)', '5': '0.764 (0.747-0.781)'}\n",
      "{'20': '0.818 (0.800-0.837)', '15': '0.808 (0.797-0.820)', '10': '0.795 (0.770-0.821)', '5': '0.764 (0.747-0.781)', '3': '0.759 (0.738-0.780)'}\n",
      "{'20': '0.818 (0.800-0.837)', '15': '0.808 (0.797-0.820)', '10': '0.795 (0.770-0.821)', '5': '0.764 (0.747-0.781)', '3': '0.759 (0.738-0.780)', '1': '0.528 (0.514-0.543)'}\n"
     ]
    }
   ],
   "source": [
    "from sklearn.model_selection import StratifiedKFold\n",
    "from xgboost import XGBClassifier\n",
    "import pandas as pd \n",
    "import numpy as np\n",
    "from sklearn.metrics import roc_curve, auc\n",
    "from math import sqrt\n",
    "\n",
    "top_n = [20, 15, 10, 5, 3, 1]\n",
    "cv = StratifiedKFold(n_splits=5)\n",
    "aucs = {}\n",
    "\n",
    "x = pd.DataFrame(data_dict['x'], columns=data_dict['features'])\n",
    "y = data_dict['y']\n",
    "\n",
    "for n in top_n:\n",
    "    _aucs = []\n",
    "    model = XGBClassifier()\n",
    "    _x = x[labels[0:n]].values\n",
    "    \n",
    "    for train, test in cv.split(_x, y):\n",
    "        model.fit(_x[train], y[train])\n",
    "        \n",
    "        probas_ = model.predict_proba(_x[test])\n",
    "        fpr, tpr, thresholds = roc_curve(y[test], probas_[:, 1])\n",
    "        _aucs.append(auc(fpr, tpr))\n",
    "        \n",
    "    mean_auc = np.mean(_aucs)\n",
    "    _ci = 1.96 * (np.std(_aucs) / sqrt(5))\n",
    "    aucs[str(n)] = \"{:.3f} ({:.3f}-{:.3f})\".format(mean_auc,\n",
    "                                              mean_auc - _ci,\n",
    "                                              mean_auc + _ci)\n",
    "    print(aucs)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2020-06-26 13:10:06,857 - root - INFO - clinical_validation : 73 - Reading data from file: model_3_out_3_maindb.csv\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\logging\\handlers.py\", line 69, in emit\n",
      "    self.doRollover()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\logging\\handlers.py\", line 393, in doRollover\n",
      "    self.rotate(self.baseFilename, dfn)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\logging\\handlers.py\", line 110, in rotate\n",
      "    os.rename(source, dest)\n",
      "PermissionError: [WinError 32] Het proces heeft geen toegang tot het bestand omdat het door een ander\n",
      "proces wordt gebruikt: 'E:\\\\Projecten\\\\Sepsis\\\\src\\\\logging\\\\scripts.log' -> 'E:\\\\Projecten\\\\Sepsis\\\\src\\\\logging\\\\scripts.log.2020-06-24_14'\n",
      "Call stack:\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\traitlets\\config\\application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 499, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 132, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\asyncio\\base_events.py\", line 539, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\asyncio\\base_events.py\", line 1775, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\ioloop.py\", line 758, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\stack_context.py\", line 300, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 1233, in inner\n",
      "    self.run()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 1147, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 346, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 259, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 513, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 294, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2817, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2843, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 67, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3018, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3183, in run_ast_nodes\n",
      "    if (yield from self.run_code(code, result)):\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3265, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-29-657357b8240c>\", line 7, in <module>\n",
      "    version = model_version_mort)\n",
      "  File \"E:\\Projecten\\Sepsis\\src\\xgboost2\\clinical_validation.py\", line 73, in read_data\n",
      "    logging.info(\"Reading data from file: {}\".format(model_file))\n",
      "Message: 'Reading data from file: model_3_out_3_maindb.csv'\n",
      "Arguments: ()\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2020-06-26 13:10:07,986 - root - INFO - clinical_validation : 88 - Selecting Y-value\n",
      "2020-06-26 13:10:07,989 - root - INFO - clinical_validation : 91 - Selecting X-values\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\logging\\handlers.py\", line 69, in emit\n",
      "    self.doRollover()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\logging\\handlers.py\", line 393, in doRollover\n",
      "    self.rotate(self.baseFilename, dfn)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\logging\\handlers.py\", line 110, in rotate\n",
      "    os.rename(source, dest)\n",
      "PermissionError: [WinError 32] Het proces heeft geen toegang tot het bestand omdat het door een ander\n",
      "proces wordt gebruikt: 'E:\\\\Projecten\\\\Sepsis\\\\src\\\\logging\\\\scripts.log' -> 'E:\\\\Projecten\\\\Sepsis\\\\src\\\\logging\\\\scripts.log.2020-06-24_14'\n",
      "Call stack:\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\traitlets\\config\\application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 499, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 132, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\asyncio\\base_events.py\", line 539, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\asyncio\\base_events.py\", line 1775, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\ioloop.py\", line 758, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\stack_context.py\", line 300, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 1233, in inner\n",
      "    self.run()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 1147, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 346, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 259, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 513, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 294, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2817, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2843, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 67, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3018, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3183, in run_ast_nodes\n",
      "    if (yield from self.run_code(code, result)):\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3265, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-29-657357b8240c>\", line 7, in <module>\n",
      "    version = model_version_mort)\n",
      "  File \"E:\\Projecten\\Sepsis\\src\\xgboost2\\clinical_validation.py\", line 88, in read_data\n",
      "    logging.info(\"Selecting Y-value\")\n",
      "Message: 'Selecting Y-value'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\logging\\handlers.py\", line 69, in emit\n",
      "    self.doRollover()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\logging\\handlers.py\", line 393, in doRollover\n",
      "    self.rotate(self.baseFilename, dfn)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\logging\\handlers.py\", line 110, in rotate\n",
      "    os.rename(source, dest)\n",
      "PermissionError: [WinError 32] Het proces heeft geen toegang tot het bestand omdat het door een ander\n",
      "proces wordt gebruikt: 'E:\\\\Projecten\\\\Sepsis\\\\src\\\\logging\\\\scripts.log' -> 'E:\\\\Projecten\\\\Sepsis\\\\src\\\\logging\\\\scripts.log.2020-06-24_14'\n",
      "Call stack:\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\traitlets\\config\\application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 499, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 132, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\asyncio\\base_events.py\", line 539, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\asyncio\\base_events.py\", line 1775, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\ioloop.py\", line 758, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\stack_context.py\", line 300, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 1233, in inner\n",
      "    self.run()\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 1147, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 346, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 259, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 513, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\tornado\\gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 294, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2817, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2843, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 67, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3018, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3183, in run_ast_nodes\n",
      "    if (yield from self.run_code(code, result)):\n",
      "  File \"c:\\programdata\\anaconda3\\envs\\ml_main\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3265, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-29-657357b8240c>\", line 7, in <module>\n",
      "    version = model_version_mort)\n",
      "  File \"E:\\Projecten\\Sepsis\\src\\xgboost2\\clinical_validation.py\", line 91, in read_data\n",
      "    logging.info(\"Selecting X-values\")\n",
      "Message: 'Selecting X-values'\n",
      "Arguments: ()\n"
     ]
    }
   ],
   "source": [
    "# model 1\n",
    "model = 3\n",
    "model_version_mort = 22\n",
    "\n",
    "data_dict = read_data(model = model, \n",
    "                      out = 3, # mortality\n",
    "                      version = model_version_mort)\n",
    "\n",
    "labels = ['BGbinary', 'VB12SE', 'URESE', 'ALBSE', 'MAGSE',\n",
    "         'TRC', 'GCS', 'FIO2', 'Geboortedatum', 'Temperatuur', \n",
    "          'GLUVB','RR_syst', 'KRESE', 'Num_vars', 'AFSE',\n",
    "          'ALTSE', 'AF_in_VG', 'HBOAB', 'TBISE', 'TCASE']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'20': '0.828 (0.799-0.856)'}\n",
      "{'20': '0.828 (0.799-0.856)', '15': '0.816 (0.790-0.842)'}\n",
      "{'20': '0.828 (0.799-0.856)', '15': '0.816 (0.790-0.842)', '10': '0.798 (0.764-0.832)'}\n",
      "{'20': '0.828 (0.799-0.856)', '15': '0.816 (0.790-0.842)', '10': '0.798 (0.764-0.832)', '5': '0.759 (0.743-0.776)'}\n",
      "{'20': '0.828 (0.799-0.856)', '15': '0.816 (0.790-0.842)', '10': '0.798 (0.764-0.832)', '5': '0.759 (0.743-0.776)', '3': '0.740 (0.699-0.782)'}\n",
      "{'20': '0.828 (0.799-0.856)', '15': '0.816 (0.790-0.842)', '10': '0.798 (0.764-0.832)', '5': '0.759 (0.743-0.776)', '3': '0.740 (0.699-0.782)', '1': '0.528 (0.514-0.543)'}\n"
     ]
    }
   ],
   "source": [
    "from sklearn.model_selection import StratifiedKFold\n",
    "from xgboost import XGBClassifier\n",
    "import pandas as pd \n",
    "import numpy as np\n",
    "from sklearn.metrics import roc_curve, auc\n",
    "from math import sqrt\n",
    "\n",
    "top_n = [20, 15, 10, 5, 3, 1]\n",
    "cv = StratifiedKFold(n_splits=5)\n",
    "aucs = {}\n",
    "\n",
    "x = pd.DataFrame(data_dict['x'], columns=data_dict['features'])\n",
    "y = data_dict['y']\n",
    "\n",
    "for n in top_n:\n",
    "    _aucs = []\n",
    "    model = XGBClassifier()\n",
    "    _x = x[labels[0:n]].values\n",
    "    \n",
    "    for train, test in cv.split(_x, y):\n",
    "        model.fit(_x[train], y[train])\n",
    "        \n",
    "        probas_ = model.predict_proba(_x[test])\n",
    "        fpr, tpr, thresholds = roc_curve(y[test], probas_[:, 1])\n",
    "        _aucs.append(auc(fpr, tpr))\n",
    "        \n",
    "    mean_auc = np.mean(_aucs)\n",
    "    _ci = 1.96 * (np.std(_aucs) / sqrt(5))\n",
    "    aucs[str(n)] = \"{:.3f} ({:.3f}-{:.3f})\".format(mean_auc,\n",
    "                                              mean_auc - _ci,\n",
    "                                              mean_auc + _ci)\n",
    "    print(aucs)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
